### ISSUE TITLE
Missing reference to Chancellor

### ISSUE THREAD

**Issue by gsmith98** [mouseexe/magic-turing-machine#1]
"The new Trilobite will have to choose a target to deal damage to, and thanks to a pair of Ivory Masks (one for us, one donated to our opponent) and hacked Crystalline Slivers, the only legal target is Azras, Beebles, and Citizens are all Trilobites thanks to a hacked Dralnu's Crusade."

I think you lost part of this sentence here.

"... the only legal target is **Chancellor of the Spires since** Azras, Beebles, and Citizens ..."

**Comment by gsmith98** [comment]
I am absolutely in love with what you've done here by the way!

**Comment by mouseexe** [comment]
I knew I forgot to finish the sentence! Thanks for finding that! Closed as it has now been fixed.

Thank you a ton for your comments, I appreciate the feedback!
