### ISSUE TITLE
Bazaar Trader can't give the opponent an Ivory Mask

### ISSUE THREAD

**Issue by gsmith98** [mouseexe/magic-turing-machine#4]
"... The new Trilobite will have to choose a target to deal damage to, and thanks to a pair of Ivory Masks (one for us, one donated to our opponent) and hacked Crystalline Slivers, ..."

Unless I'm missing something you haven't actually included a way to give your opponent an Ivory Mask since Bazaar Trader only donates artifacts, creatures, or lands. (And the Clever Impersonator token that ETB's as an Ivory Mask is never a creature the Trader can target.) One Donate (the Urza's Destiny card) should do the trick.

**Comment by gsmith98** [comment]
I believe another option is to use Aegis of the Gods instead of Ivory Mask.

**Comment by gsmith98** [comment]
I believe another option is to use True Believer instead of Ivory Mask.

**Comment by mouseexe** [comment]
True Believer is the way to go! I'll have that in my updated version. Closing as a solution has been found.
